bookmarks/urls.py
from django.conf.urls.defaults import patterns, url
from bookmarks import views


urlpatterns = patterns('',
	url(r'^$', views.ListBookmarksView.as_view(), name='bookmarks_list'),	
	url(r'^tagged/(?P<tags>[a-zA-Z0-9+-_]+)/$',
		views.TaggedBookmarksView.as_view(), name='bookmarks_tagged'),
	url(r'^hostname/(?P<hostname>.+)/$', views.HostnameBookmarksView.as_view(),
		name='bookmarks_hostname'),
	
	url(r'^new/$', views.CreateBookmarkView.as_view(), name='bookmark_create'),
	url(r'^edit/(?P<id>\d+)/$', views.EditBookmarkView.as_view(), name='bookmark_edit'),
)

can_o_beans/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib.sitemaps import FlatPageSitemap, GenericSitemap
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from journal.models import JournalEntry

from django.contrib import admin
admin.autodiscover()


journal_sitemap_info_dict = {
    'queryset': JournalEntry.objects.filter(published=True),
    'date_field': 'published_on'
}


sitemaps = {
    'flatpages': FlatPageSitemap,
    'journal': GenericSitemap(journal_sitemap_info_dict)
}


urlpatterns = patterns('',
    url(r'^accounts/login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', name='logout'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^journal/', include('journal.urls')),
    url(r'^bookmarks/', include('bookmarks.urls')),
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
)

urlpatterns += staticfiles_urlpatterns()

journal/urls.py
from django.conf.urls.defaults import patterns, include, url
from journal import views

y = '(?P<year>\d{4})'
m = '(?P<month>\w+)'
d = '(?P<day>\d{1,2})'
s = '(?P<slug>\S+)'
k = '(?P<pk>\d+)'
p = '(?P<page>\d+)'

urlpatterns = patterns('',
    url('^$', views.JournalIndexView.as_view(),
        name='cob_journal_index'),
    url('^page/{0}/'.format(p), views.JournalIndexView.as_view(),
        name='cob_journal_index_paginated'),

    url('^{0}/{1}/{2}/{3}/$'.format(y, m, d, s), views.EntryView.as_view(),
        name='cob_journal_entry_detail_view'),

    url(r'^new/', views.CreateJournalEntryView.as_view(),
    	name='journal_entry_new'),
    url(r'^edit/(?P<pk>\d+)/$', views.EditJournalEntryView.as_view(),
    	name='journal_entry_edit'),

    url(r'^feed/$', views.LatestEntriesFeed(), name='feed_view'),
)

bookmarks/models.py
from django.db import models
from urlparse import urlparse
from taggit.managers import TaggableManager


class Bookmark(models.Model):
	created = models.DateTimeField(auto_now_add=True)
	modified = models.DateTimeField(auto_now=True)
	title = models.TextField()
	url = models.URLField()
	hostname = models.TextField(blank=True)
	tags = TaggableManager(blank=True)
	note = models.TextField(blank=True)
	private = models.BooleanField(default=False)

	def __unicode__(self):
		return self.title

	def save(self, *args, **kwargs):
		self.hostname = urlparse(self.url).hostname
		super(Bookmark, self).save(*args, **kwargs)

bookmarks/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from bookmarks.models import Bookmark


class BookmarkForm(forms.ModelForm):
	class Meta:
		model = Bookmark
		widgets = {
			'title': forms.TextInput()
		}
		exclude = ('hostname',)

	def __init__(self, *args, **kwargs):
		self.helper = FormHelper()
		self.helper.form_class = 'cob-form'
		self.helper.form_method = 'post'
		self.helper.form_action = 'bookmark_create'
		
		self.helper.add_input(Submit('submit', 'Submit'))
		super(BookmarkForm, self).__init__(*args, **kwargs)

bookmarks/views.py
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView
from bookmarks.models import Bookmark
from bookmarks.forms import BookmarkForm
from gravy.utils import StaffMemberRequiredMixin


BOOKMARKS_PER_PAGE = 50


class ListBookmarksView(ListView):
	template_name = 'bookmarks/bookmarks_list.html'
	paginate_by = BOOKMARKS_PER_PAGE

	def get_queryset(self):
		if self.request.user.is_authenticated():
			return Bookmark.objects.order_by('-created')
		else:
			return Bookmark.objects.filter(private=False).order_by('-created')


class TaggedBookmarksView(ListView):
	template_name = 'bookmarks/bookmarks_tagged.html'
	paginate_by = BOOKMARKS_PER_PAGE

	def _get_tags(self):
		return self.kwargs['tags'].split('+')

	def get_queryset(self):
		# This is very inefficient, but it won't be an issue during actual
		# operation since the number of tags is likely to be very small (mostly
		# just one).
		
		tags = self._get_tags()
		qs = Bookmark.objects.all()
		
		for tag in tags:
			qs = qs.filter(tags__name__in=[tag,])
		
		return qs

	def get_context_data(self, *args, **kwargs):
		context = super(TaggedBookmarksView, self).get_context_data(
			*args, **kwargs
		)

		context['tags'] = self._get_tags()
		return context


class HostnameBookmarksView(ListView):
	template_name = 'bookmarks/bookmarks_hostname.html'
	paginate_by = BOOKMARKS_PER_PAGE

	def get_queryset(self):
		return Bookmark.objects.filter(hostname=self.kwargs['hostname'])

	def get_context_data(self, *args, **kwargs):
		context = super(HostnameBookmarksView, self).get_context_data(
			*args, **kwargs
		)

		context['hostname'] = self.kwargs['hostname']
		return context


class CreateBookmarkView(StaffMemberRequiredMixin, CreateView):
	model = Bookmark
	template_name = 'bookmarks/bookmark_create.html'
	form_class = BookmarkForm
	success_url = reverse_lazy('bookmarks_list')

	def get_initial(self, *args, **kwargs):
		initial = super(CreateBookmarkView, self).get_initial(*args, **kwargs)
		
		initial['title'] = self.request.GET.get('title', '')
		initial['url'] = self.request.GET.get('url', '')
		
		return initial


class EditBookmarkView(StaffMemberRequiredMixin, UpdateView):
	pass

bookmarks/templates/bookmarks/bookmark_create.html
{% extends "gravy/base.html" %}
{% load crispy_forms_tags %}

{% block title %}New Bookmark{% endblock title %}

{% block content %}
	<div class="content-block">
		<h2>Add Bookmark</h2>
		<a class="label" href="{% url bookmarks_list %}">show all bookmarks</a>
		
		{% crispy form %}
	</div>

{% endblock content %}

bookmarks/templates/bookmarks/bookmarks_hostname.html
{% extends "gravy/base.html" %}

{% block title %}All bookmarks from {{ hostname }}{% endblock title %}

{% block content %}
	<div class="content-block">
		<h2>All Bookmarks from <i>{{ hostname }}</i></h2>
		<a class="label" href="{% url bookmarks_list %}">show all bookmarks</a>

		{% include "bookmarks/bookmarks_list_snippet.html" %}
	</div>
{% endblock content %}

{% block extraoutside_before_footer %}
		{% include "bookmarks/bookmarks_pagination_snippet.html" %}
{% endblock extraoutside_before_footer %}

bookmarks/templates/bookmarks/bookmarks_list.html
{% extends "gravy/base.html" %}
{% load humanize %}

{% block title %}Bookmarks{% endblock title %}

{% block content %}
	<div class="content-block">
		<h2>All Bookmarks</h2>
		
		{% if perms.bookmarks.add_bookmark %}
			<a class="label" href="{% url bookmark_create %}">add new</a>
		{% endif %}
		
		{% include "bookmarks/bookmarks_list_snippet.html" %}
	</div>
{% endblock content %}

{% block extraoutside_before_footer %}
		{% include "bookmarks/bookmarks_pagination_snippet.html" %}
{% endblock extraoutside_before_footer %}

bookmarks/templates/bookmarks/bookmarks_list_snippet.html
{% load humanize %}

{% if object_list %}
	{% for bookmark in object_list %}
		<div class="bookmark">
			<div class="bookmark-title">
				<a target="blank" rel="nofollow" class="bookmark-url" href="{{ bookmark.url }}">{{ bookmark.title }}</a>
				<span class="bookmark-hostname">
					(<a href="{% url bookmarks_hostname hostname=bookmark.hostname %}">{{ bookmark.hostname }}</a>)
				</span>
			</div>

			{% if bookmark.note %}
				<div class="bookmark-note">
					<p>{{ bookmark.note|safe }}</p>
				</div>
			{% endif %}
			
			<div class="bookmark-tags">
				{% for tag in bookmark.tags.all %}
					<a class="tag" href="{% url bookmarks_tagged tags=tag.name %}">{{ tag }}</a>
				{% endfor %}
			</div>
			
			<div class="bookmark-meta">
				<span class="bookmark-ago">added {{ bookmark.created|naturaltime }}</span>
				{% if perms.bookmarks.change_bookmark %}
					<a href="#">edit</a>
				{% endif %}

				{% if perms.bookmarks.delete_bookmark %}
					<a href="#">delete</a>
				{% endif %}
			</div>
		</div>
	{% endfor %}
{% else %}
	<p>Sorry, no bookmarks found.</p>
{% endif %}

bookmarks/templates/bookmarks/bookmarks_pagination_snippet.html
<div class="pagination outside-block">
    {% if page_obj.has_previous %}
        <a class="label" href="?page={{ page_obj.previous_page_number }}">← prev</a>
    {% else %}
        <span class="label disabled">← prev</span>
    {% endif %}

    <span class="current">
        page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
    </span>

    {% if page_obj.has_next %}
        <a class="label" href="?page={{ page_obj.next_page_number }}">next →</a>
    {% else %}
    	<span class="label disabled">next →</span>
	{% endif %}
</div>

bookmarks/templates/bookmarks/bookmarks_tagged.html
{% extends "gravy/base.html" %}

{% block title %}Bookmarks tagged {{ tags|join:', ' }}{% endblock title %}

{% block content %}
	<div class="content-block">
		<h2>Bookmarks tagged <i>{{ tags|join:', ' }}</i></h2>
		<a class="label" href="{% url bookmarks_list %}">show all bookmarks</a>

		{% include "bookmarks/bookmarks_list_snippet.html" %}
	</div>
{% endblock content %}

{% block extraoutside_before_footer %}
		{% include "bookmarks/bookmarks_pagination_snippet.html" %}
{% endblock extraoutside_before_footer %}